### PR TITLE
Document the `include_stops` parameter on a route request

### PR DESCRIPTION
**Pull request by toofishes**
This currently works as expected, but is undocumented. I sorted the three `include_*` parameters in alpha order.

### CODE REVIEW

**Comment by irees** [comment]
@toofishes 

This PR is a bit topical, as we've been having some discussions on this particular REST API parameter (and which is why it's currently undocumented.) I'll get back to you this week on the plans; it may be an option that is enabled/disabled per deployment or via permission levels, and I'll need to find a way to note this in the OpenAPI description (possibly using an `x-role-required` extension or something similar; we use some of these extensions for custom rendering options on the public transit.land documentation page.)

Also, the `rest.json` OpenAPI description is automatically generated; I'll see if I can find a way to make that clear in the file itself. The file is generated using parameter descriptions included in each REST API handler, and the response description is generated using the associated GraphQL query document. [Example](https://github.com/interline-io/transitland-server/blob/dca9df4d16bcb4aef5241c9a3e93612910705bb3/server/rest/stop_request.go#L54); you could add another parameter here similarly to how you added it in the json file. The generator code is in `docs/openapi/gen.go` and can be run with `go generate` in that directory.

**Comment by toofishes** [comment]
Thanks for the pointers- I'll get this updated in the correct way and let you know when it is ready for re-review!

**Comment by toofishes** [comment]
Updated the PR- this also required updating the documentation generation code to reflect the new custom scalar types recently introduced, otherwise things errored out.

**Comment by irees** [comment]
@toofishes 

Thank you for the changes - everything looks good and I plan to merge. I just noticed that GitHub actions isn't configured to run on PRs from forks, so I'm enabling that now and may try to run it before the merge.

Note: I may add an `x-` annotation later on to some parameters to render additional information on our public documentation site, which uses this file.

**Pull request merged**
